global:
  domain: <DOMAIN_NAME>
  imagePullSecret:
    {}
srv:
  bindings:
    messaging:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-messaging
    destination:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-destination
  image:
    repository: <DOCKER_ACCOUNT>/kymamock
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health