apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-githubtools
  namespace: {{.Values.namespace}}
  labels:
     name: kyma-cap-s4ems
type: opaque
data:
  username: {{.Values.gitusername}}
  password: {{.Values.gitpassword}}