apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-qrcodeconfig
  namespace: {{.Values.namespace}}
  labels:
     name: kyma-cap-s4ems
data:
  http_proxy: {{.Values.functionshttpproxy}}
  destination_name: | 
   {{.Values.functionsenv}}
 