# Helm global values, for more information, see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values
global:
  # Image Pull Secret configuration, for more information, see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecret: {}
  # Name of the Kubernetes Secret, used as an image pull secret (must be of type kubernetes.io/dockerconfigjson). Can't be used with the `dockerconfigjson` option.
  # name: ""
  # The content for the dynamically generated Kubernetes Secret, which will be used as an image pull secret. Can't be used with the `name` option.
  # dockerconfigjson: ""
  # Either name or repository is required.
  image: {}
  # registry: gcr.io/my-project
  # tag: latest

  sap:
    _internal:
      content-deployment:
        versions:
          1.6.0: true
# Will be used instead of the `.Chart.Name`, e.g. when generating the Deployment name.
# nameOverride: name

# Will be used as an override for the `.fullname` helper function (i.e. `.Release.Name-.Chart.Name`).
# fullnameOverride: my-name

# Name of the Service Account assigned to pods.
# serviceAccountName: my-serviceaccount

# The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified.
# runAsUser: 1000
image: {}
# Should also include the image name (i.e. everything before the `:` sign).
# repository: repo/image
# registry: gcr.io/my-project
# tag: latest

# Image Pull Secret configuration, for more information, see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecret: {}
# Name of the Kubernetes Secret, used as an image pull secret (must be of type kubernetes.io/dockerconfigjson). Can't be used with the `dockerconfigjson` option.
# name: ""
# The content for the dynamically generated Kubernetes Secret, which will be used as an image pull secret. Can't be used with the `name` option.
# dockerconfigjson: ""

# Pod resources configuration, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ for more information
# resources:
#   limits:
#     cpu: 100m
#     ephemeral-storage: 1G
#     memory: 1G
#   requests:
#     cpu: 100m
#     ephemeral-storage: 1G
#     memory: 1G
env: {}
# env:
#   key1: value
#   key2:
#     secretKeyRef:
#       name: my-secret
#       key: my-key
#   key3:
#     configMapKeyRef:
#       name: my-configmap
#       key: my-key
# Also can be specified as a list
# env:
#   - name: key1
#     value: value1
#   - name: key2
#     configMapKeyRef:
#       name: my-configmap
#       key: my-key
envFrom: []
# - configMapRef:
#     name: my-configmap1
# - secretRef:
#     name: my-secret-ref1

ttlDaysAfterFinished: 14
# bindings:
#   ui5-repo-servicerepo:
#     serviceInstanceName: ui5-repo-instance
#     externalName: ui5-kyma-binding
#     secretName: ui5-repo-binding-secret
#     parameters:
#       foo: bar
#     parametersFrom:
#       - secretKeyRef:
#           key: test
#           name: test
#     credentialsRotationPolicy:
#       enabled: true
#   hana:
#     serviceInstanceName: hana-manual
#   portal:
#     fromSecret: manual-secret # user-provided-service

## Annotations to add to objects
annotations:
  ## Annotations to add to the Job and underlying Pods
  job: {}
