{{ if .Values.expose.enabled}}
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ include "web-application.fullname" . }}
  labels: {{- include "web-application.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.expose.gateway }}
  host: {{ include "web-application.exposeHost" . }}
  service:
    name: {{ include "web-application.fullname" . }}
    port: {{ .Values.port }}
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
{{ end }}
