apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "web-application.labels" . | nindent 4 }}
  name: {{ include "web-application.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "web-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "web-application.selectorLabels" . | nindent 8 }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/{{ include "web-application.name" . }}: runtime/default
    spec:
      {{- if (include "web-application.imagePullSecretName" .) }}
      imagePullSecrets:
        - name: {{ include "web-application.imagePullSecretName" . }}
      {{- end }}
      automountServiceAccountToken: false
      serviceAccountName: {{ tpl (.Values.serviceAccountName | default (include "web-application.fullname" .)) $ }}
      containers:
      - image: {{ include "web-application.imageName" . }}
        name: {{ include "web-application.name" . }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        envFrom:
        {{- $envFromVars := (include "web-application.processEnvFrom" . | fromJson) }}
        {{- if not (eq (len $envFromVars.vars) 0) }}
        {{- $envFromVars.vars | toYaml | nindent 8}}
        {{- end }}
        env:
        {{- if .Values.bindings }}
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        {{- end }}
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: TMPDIR
          value: /tmp
        {{- $envVars := (include "web-application.processEnv" $ | fromJson) }}
        {{- if not (eq (len $envVars.vars) 0) }}
        {{- $envVars.vars | toYaml | nindent 8}}
        {{- end }}
        {{- if not $envVars.appName}}
        - name: APPLICATION_NAME
          value: {{ include "web-application.fullname" . }}
        {{- end }}
        {{- if not $envVars.appURI}}
        - name: APPLICATION_URI
          value: {{ include "web-application.applicationUri" . }}
        {{- end }}
        {{- $health := .Values.health_check | default .Values.health }}
        livenessProbe:
        {{- if $health.liveness.path }}
          httpGet:
            path: {{ $health.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        readinessProbe:
        {{- if $health.readiness.path }}
          httpGet:
            path: {{ $health.readiness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
        startupProbe:
        {{- if $health.liveness.path }}
          httpGet:
            path: {{ $health.liveness.path }}
            port: http
        {{- else }}
          tcpSocket:
            port: {{ .Values.port }}
        {{- end }}
          {{- $startupTimeout := .Values.startupTimeout | default .Values.startupTimeoutSeconds }}
          failureThreshold: {{ div (add1  $startupTimeout) 2 }}
          periodSeconds: 2
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- range $volume := .Values.additionalVolumes }}
        - name: {{ $volume.name | quote }}
          {{- toYaml $volume.volumeMount  | nindent 10 }}
        {{- end }}
        {{- include "web-application.serviceMounts" . | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
      {{- if (include "web-application.ha" .) }}
      topologySpreadConstraints:
      {{- range $constraint := .Values.availability.topologySpreadConstraints }}
      - labelSelector:
          matchLabels: {{- include "web-application.selectorLabels" $ | nindent 12 }}
        maxSkew: {{ $constraint.maxSkew }}
        topologyKey: {{ $constraint.topologyKey }}
        whenUnsatisfiable: {{ $constraint.whenUnsatisfiable }}
      {{- end }}
      {{- end }}
      volumes:
      - emptyDir: {}
        name: tmp
      {{- include "web-application.serviceVolumes" . | nindent 6 }}
      {{- range $volume := .Values.additionalVolumes }}
      -
        {{- tpl (omit $volume "volumeMount" | toYaml) $ | nindent 8 }}
      {{- end }}
